### ISSUE TITLE
audacity updated to 2.30

### ISSUE THREAD

**Issue by Lvaskz** [probonopd/audacity#12]
Hi, can you update it to 2.30?

**Comment by ghost** [comment]
I also interested in updating to `Audacity-2.3.0-*.AppImage` ;-)

**Comment by probonopd** [comment]
2.3.0 is 9a45c02. And inofficial 9a45c02 AppImages (built by me) are available for download on https://github.com/probonopd/audacity/releases.

Please ask the Audactiy team to provide and support official AppImages. Thanks.
