### ISSUE TITLE
Icon from dock ubunt 18.04 is missing

### ISSUE THREAD

**Issue by Lvaskz** [probonopd/audacity#13]
Hi, I install it by appimagelauncher, but icon from dock is missing.

**Comment by probonopd** [comment]
Thanks for reporting. I don't have the time to look into it right now but maybe @TheAssassin could have a look? From a first glance, the AppImage seems to contain the icons in the correct places:

```
$ find squashfs-root/usr/share/icons/
squashfs-root/usr/share/icons/
squashfs-root/usr/share/icons/hicolor
squashfs-root/usr/share/icons/hicolor/48x48
squashfs-root/usr/share/icons/hicolor/48x48/apps
squashfs-root/usr/share/icons/hicolor/48x48/apps/audacity.png
squashfs-root/usr/share/icons/hicolor/scalable
squashfs-root/usr/share/icons/hicolor/scalable/apps
squashfs-root/usr/share/icons/hicolor/scalable/apps/audacity.svg
squashfs-root/usr/share/icons/hicolor/32x32
squashfs-root/usr/share/icons/hicolor/32x32/apps
squashfs-root/usr/share/icons/hicolor/32x32/apps/audacity.png
squashfs-root/usr/share/icons/hicolor/16x16
squashfs-root/usr/share/icons/hicolor/16x16/apps
squashfs-root/usr/share/icons/hicolor/16x16/apps/audacity.png
squashfs-root/usr/share/icons/hicolor/22x22
squashfs-root/usr/share/icons/hicolor/22x22/apps
squashfs-root/usr/share/icons/hicolor/22x22/apps/audacity.png
squashfs-root/usr/share/icons/hicolor/24x24
squashfs-root/usr/share/icons/hicolor/24x24/apps
squashfs-root/usr/share/icons/hicolor/24x24/apps/audacity.png
```

**Comment by TheAssassin** [comment]
@Lvaskz which exact AppImage did you use? Please post a link.

**Comment by Lvaskz** [comment]
https://github.com/probonopd/audacity/releases/download/continuous/Audacity_for_JACK-705fc96-x86_64.AppImage
https://github.com/probonopd/audacity/releases/download/continuous/Audacity_with_FFMPEG_with_FLAC-705fc96-x86_64.AppImage
At the moment, this two.

**Comment by TheAssassin** [comment]
It works perfectly fine on xubuntu 18.04. @probonopd the AppImage seems okay, I think we can close here.

@Lvaskz please open a new issue in AppImageLauncher's repository, including a few more details on your system (distro, DE & version).

**Comment by Lvaskz** [comment]
Hi, you right @TheAssassin this bug is only in ubuntu 18.04, because in linuxmint 19 works well.
What do you need about me, for reporte this issue?

**Comment by TheAssassin** [comment]
Just put together all the information I requested in your other issue reports, and open a new issue in AppImageLauncher's repository.
