### ISSUE TITLE
Travis autobuilds might be broken?

### ISSUE THREAD

**Issue by ReNardier** [probonopd/audacity#15]
last successful build
https://travis-ci.org/github/probonopd/audacity/builds/543405458
first erroneous build
https://travis-ci.org/github/probonopd/audacity/builds/544272749
latest erroneous build
https://travis-ci.org/github/probonopd/audacity/builds/702935814
also names like "Audacity_with_FLAC-06af0c6-x86_64.AppImage" are not that good when you want to know the date of the build

**Comment by probonopd** [comment]
Hi @ReNardier thanks for posting. Unfortunately the Audacity project never came around to publishing an AppImage, so I lost interest in the effort. Would you like to take over from here?

**Comment by probonopd** [comment]
Please let the Audacity project know if you would like to see an official AppImage. We can look into this again should the project decide to publish and support an AppImage.
