### ISSUE TITLE
Help / manual fails to open

### ISSUE THREAD

**Issue by SteveDaulton** [probonopd/audacity#9]
Testing with "Audacity_with_FFMPEG_with_FLAC_for_JACK-26d72be-x86_64.AppImage" from https://github.com/probonopd/audacity/releases
Commit Id: 26d72b of Tue Dec 5 20:59:58 2017 -0500
On Xubuntu 16.04 64-bit

Whether attempting to open the manual from the help menu, or open help from one of the "?" buttons, the help page does not open. Terminal shows:

ERROR: ld.so: object '/tmp/.mount_AudacilMKb66/usr/optional/exec.soA' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/tmp/.mount_AudacilMKb66/usr/optional/exec.soA' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/tmp/.mount_AudacilMKb66/usr/optional/exec.soA' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/tmp/.mount_AudacilMKb66/usr/optional/exec.soA' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/tmp/.mount_AudacilMKb66/usr/optional/exec.soA' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
/usr/lib/firefox/firefox: relocation error: /usr/lib/firefox/firefox: symbol _ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE4copyEPcmm, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference

**Comment by probonopd** [comment]
Please retry with the latest binary . Works for me on Xubuntu 16.04 now.

**Comment by probonopd** [comment]
Hello @SteveDaulton, thanks for your report; however I am no longer working on this since the https://github.com/audacity/audacity project has not merged my [pull request](https://github.com/audacity/audacity/pull/172). We can look into this again should the project decide to publish an AppImage.
